title: Connecting a servo to your Crumble using a Crumbliser
hero_image: images/banner.png
description: servo-to-crumble-using-crumblisers description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-22"
steps:
  - title: Connecting a servo to Crumble using a Crumbliser
