title: How to use a Crumbliser to connect a servo motor to a Crumble
hero_image: images/banner.png
description: How to use a Crumbliser to connect a servo motor to a Crumble
version: 4.0.0
listed: false
copyedit: false
last_tested: "2019-05-22"
steps:
  - title: How to use a Crumbliser to connect a servo motor to a Crumble
